const languages = {
    en: {
        title: "Daily Progress",
        wakeUpLabel: "Wake-up Time:",
        sleepLabel: "Sleep Time:",
        graphTypeLabel: "Graph Type:",
        barLabel: "Bar",
        circleLabel: "Circle",
        colorLabel: "Color:",
        greenLabel: "Green",
        redLabel: "Red",
        blueLabel: "Blue",
        setButton: "Set",
        notificationMessage: "Turn off the screen and let's wrap up the day.",
        languageEN: "English",
        languageKO: "Korean",
        languageJA: "Japanese",
        languageCN: "Chinese",
        am: "AM",
        pm: "PM"
    },
    ko: {
        title: "하루 진행률",
        wakeUpLabel: "일어나는 시각:",
        sleepLabel: "잠드는 시각:",
        graphTypeLabel: "그래프 형태:",
        barLabel: "막대",
        circleLabel: "원형",
        colorLabel: "색상:",
        greenLabel: "초록",
        redLabel: "빨강",
        blueLabel: "파랑",
        setButton: "설정",
        notificationMessage: "화면을 끄고 하루를 정리합시다.",
        languageEN: "영어",
        languageKO: "한국어",
        languageJA: "일본어",
        languageCN: "중국어",
        am: "오전",
        pm: "오후"
    },
    ja: {
        title: "今日の進捗",
        wakeUpLabel: "起床時間:",
        sleepLabel: "就寝時間:",
        graphTypeLabel: "グラフの種類:",
        barLabel: "棒",
        circleLabel: "円形",
        colorLabel: "色:",
        greenLabel: "緑",
        redLabel: "赤",
        blueLabel: "青",
        setButton: "設定",
        notificationMessage: "画面を消して、一日を締めくくりましょう。",
        languageEN: "英語",
        languageKO: "韓国語",
        languageJA: "日本語",
        languageCN: "中国語",
        am: "午前",
        pm: "午後"
    },
    cn: {
        title: "每日进度",
        wakeUpLabel: "起床时间:",
        sleepLabel: "睡觉时间:",
        graphTypeLabel: "图表类型:",
        barLabel: "条形",
        circleLabel: "圆形",
        colorLabel: "颜色:",
        greenLabel: "绿色",
        redLabel: "红色",
        blueLabel: "蓝色",
        setButton: "设置",
        notificationMessage: "请关掉屏幕，结束今天吧。",
        languageEN: "英语",
        languageKO: "韩语",
        languageJA: "日语",
        languageCN: "中文",
        am: "上午",
        pm: "下午"
    }
};
