const languages = {
    en: {
        title: "Daily Progress",
        wakeUpLabel: "Wake-up Time:",
        sleepLabel: "Sleep Time:",
        graphTypeLabel: "Graph Type:",
        barLabel: "Bar",
        circleLabel: "Circle",
        colorLabel: "Color:",
        greenLabel: "Green",
        redLabel: "Red",
        blueLabel: "Blue",
        setButton: "Set",
        notificationMessage: "Turn off the screen and let's wrap up the day.",
        languageEN: "English",
        languageKO: "Korean",
        languageJA: "Japanese",
        languageCN: "Chinese",
        am: "AM",
        pm: "PM",
        updateButton: "Check for Updates",
        updateAvailable: "New version ({latestVersion}) available! (Current: {currentVersion}) Downloading...",
        updateNotAvailable: "You are on the latest version ({currentVersion}).",
        updateDownloaded: "Update downloaded.",
        restartAndInstall: "Restart to Install",
        updateErrorMsg: "An error occurred while checking for updates. Please try again later."
    },
    ko: {
        title: "하루 진행률",
        wakeUpLabel: "일어나는 시각:",
        sleepLabel: "잠드는 시각:",
        graphTypeLabel: "그래프 형태:",
        barLabel: "막대",
        circleLabel: "원형",
        colorLabel: "색상:",
        greenLabel: "초록",
        redLabel: "빨강",
        blueLabel: "파랑",
        setButton: "설정",
        notificationMessage: "화면을 끄고 하루를 정리합시다.",
        languageEN: "영어",
        languageKO: "한국어",
        languageJA: "일본어",
        languageCN: "중국어",
        am: "오전",
        pm: "오후",
        updateButton: "업데이트 확인",
        updateAvailable: "새 버전({latestVersion})이 있습니다! (현재: {currentVersion}) 다운로드 중...",
        updateNotAvailable: "최신 버전({currentVersion})을 사용 중입니다.",
        updateDownloaded: "업데이트가 다운로드되었습니다.",
        restartAndInstall: "재시작하여 설치",
        updateErrorMsg: "업데이트 확인 중 오류가 발생했습니다. 나중에 다시 시도해주세요."
    },
    ja: {
        title: "今日の進捗",
        wakeUpLabel: "起床時間:",
        sleepLabel: "就寝時間:",
        graphTypeLabel: "グラフの種類:",
        barLabel: "棒",
        circleLabel: "円形",
        colorLabel: "色:",
        greenLabel: "緑",
        redLabel: "赤",
        blueLabel: "青",
        setButton: "設定",
        notificationMessage: "画面を消して、一日を締めくくりましょう。",
        languageEN: "英語",
        languageKO: "韓国語",
        languageJA: "日本語",
        languageCN: "中国語",
        am: "午前",
        pm: "午後",
        updateButton: "更新を確認",
        updateAvailable: "新しいバージョン({latestVersion})があります！ (現在: {currentVersion}) ダウンロード中...",
        updateNotAvailable: "最新バージョン({currentVersion})を使用しています。",
        updateDownloaded: "アップデートがダウンロードされました。",
        restartAndInstall: "再起動してインストール",
        updateErrorMsg: "更新の確認中にエラーが発生しました。後でもう一度お試しください。"
    },
    cn: {
        title: "每日进度",
        wakeUpLabel: "起床时间:",
        sleepLabel: "睡觉时间:",
        graphTypeLabel: "图表类型:",
        barLabel: "条形",
        circleLabel: "圆形",
        colorLabel: "颜色:",
        greenLabel: "绿色",
        redLabel: "红色",
        blueLabel: "蓝色",
        setButton: "设置",
        notificationMessage: "请关掉屏幕，结束今天吧。",
        languageEN: "英语",
        languageKO: "韩语",
        languageJA: "日语",
        languageCN: "中文",
        am: "上午",
        pm: "下午",
        updateButton: "检查更新",
        updateAvailable: "新版本({latestVersion})可用！ (当前: {currentVersion}) 正在下载...",
        updateNotAvailable: "您使用的是最新版本({currentVersion})。",
        updateDownloaded: "更新已下载。",
        restartAndInstall: "重启以安装",
        updateErrorMsg: "检查更新时发生错误。请稍后再试。"
    }
};
